[network]
name = "devnet"

[network.deployment]
deployment_fee_rate = 15

[network.accounts]
deployer = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
wallet_1 = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
wallet_2 = "ST2CY5V39NHDPWSXMW3Q3TCVEM9N2T3W5N6K8G5WS"
wallet_3 = "ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC"
wallet_4 = "ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND"
wallet_5 = "ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB"
wallet_6 = "ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0"
wallet_7 = "ST3PF13W7Z0RRM42A8VZRVGQ76WF1RVBRQ1QP6C3"
wallet_8 = "ST3NBRSFKX28FQ2ZJ1FAKXW6VAFCER7EB68XSRQ47"
wallet_9 = "STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6"

[[network.contracts]]
name = "world-citizenship-nft"
path = "contracts/world-citizenship-nft.clar"
clarity_version = "2.1"

[network.contracts.world-citizenship-nft.deploy]
deployer = "deployer"
at_block = 0

[[network.contracts]]
name = "world-citizenship-dao"
path = "contracts/world-citizenship-dao.clar"
clarity_version = "2.1"

[network.contracts.world-citizenship-dao.deploy]
deployer = "deployer"
at_block = 1
